name: Lint (Ruff and Mypy)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Lint with Ruff
      run: |
        pip install ruff
        ruff check . --output-format=github

    - name: Lint with Mypy
      run: |
        pip install mypy
        mypy . --config-file pyproject.toml --ignore-missing-imports --no-namespace-packages
