[theme]
base="light"
primaryColor="#ff6347"
backgroundColor="#fafafa"
secondaryBackgroundColor="#dcdcdc"
textColor="#222"
font="sans serif"
borderColor="#4CAF50"
borderRadius="8px"
buttonPrimaryColor="#800080"
buttonSecondaryColor="#008000"